//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITHelp_Data_Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asset()
        {
            this.Asset_Tickets = new HashSet<Asset_Tickets>();
        }
    
        public int Id { get; set; }
        public int Type_Id { get; set; }
        public int Location_Id { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Bought { get; set; }
        public Nullable<int> Supplier_Id { get; set; }
    
        public virtual Asset_Suppliers Asset_Suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset_Tickets> Asset_Tickets { get; set; }
        public virtual Asset_Types Asset_Types { get; set; }
        public virtual Location Location { get; set; }
    }
}
