//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITHelp_Data_Service.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asset_Suppliers> Asset_Suppliers { get; set; }
        public virtual DbSet<Asset_Tickets> Asset_Tickets { get; set; }
        public virtual DbSet<Asset> Assets { get; set; }
        public virtual DbSet<Keyword> Keywords { get; set; }
        public virtual DbSet<Knowledge> Knowledges { get; set; }
        public virtual DbSet<Knowledge_Keywords> Knowledge_Keywords { get; set; }
        public virtual DbSet<Ticket_History> Ticket_History { get; set; }
        public virtual DbSet<Ticket_Keywords> Ticket_Keywords { get; set; }
        public virtual DbSet<Ticket_Statuses> Ticket_Statuses { get; set; }
        public virtual DbSet<Ticket_Types> Ticket_Types { get; set; }
        public virtual DbSet<Ticket_Urgencies> Ticket_Urgencies { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Asset_Types> Asset_Types { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
    }
}
