//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITHelp_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public int Id { get; set; }
        public int Type_Id { get; set; }
        public int Location_Id { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Bought { get; set; }
        public Nullable<int> Supplier_Id { get; set; }
    
        public virtual Asset_Suppliers Asset_Suppliers { get; set; }
        public virtual Asset_Types Asset_Types { get; set; }
        public virtual Location Location { get; set; }
    }
}
