//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITHelp_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset_Tickets
    {
        public int Asset_Id { get; set; }
        public int Ticket_Id { get; set; }
        public int Id { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
